//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eForm.Approve.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eForm.Approve.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://edocdev.apps.thaibev.com/oacapi/api/BevLifeProducerToApproval.
        /// </summary>
        internal static string apiBevApprove {
            get {
                return ResourceManager.GetString("apiBevApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://eactdev.thaibev.com/Base/Image/?s=attachment&amp;amp;f={0}.
        /// </summary>
        internal static string controllerGetFile {
            get {
                return ResourceManager.GetString("controllerGetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;a href=&amp;quot;{0} &amp;quot; &amp;gt; {1} &amp;lt;/a&amp;gt;.
        /// </summary>
        internal static string formatLinkfiles {
            get {
                return ResourceManager.GetString("formatLinkfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\logs\logs_{1}.txt.
        /// </summary>
        internal static string logsFileName {
            get {
                return ResourceManager.GetString("logsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=10.5.56.33; Initial Catalog=DBEAct_DEV;User ID=rtmDev;password=ThaibevRTM@DB101;Max Pool Size=200;.
        /// </summary>
        internal static string strConn {
            get {
                return ResourceManager.GetString("strConn", resourceCulture);
            }
        }
    }
}
