//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eActForm.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสบัญชี.
        /// </summary>
        public static string accountCode {
            get {
                return ResourceManager.GetString("accountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารทั้งหมด.
        /// </summary>
        public static string allDocuments {
            get {
                return ResourceManager.GetString("allDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงิน.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเงิน(บาท).
        /// </summary>
        public static string amountTHB {
            get {
                return ResourceManager.GetString("amountTHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การอนุมัติ.
        /// </summary>
        public static string approval {
            get {
                return ResourceManager.GetString("approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารขออนุมัติ.
        /// </summary>
        public static string approvalDocument {
            get {
                return ResourceManager.GetString("approvalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติการอนุมัติ.
        /// </summary>
        public static string approvalHistory {
            get {
                return ResourceManager.GetString("approvalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่อนุมัติ.
        /// </summary>
        public static string approveDate {
            get {
                return ResourceManager.GetString("approveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้อนุมัติ.
        /// </summary>
        public static string approvePerson {
            get {
                return ResourceManager.GetString("approvePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่.
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รออนุมัติ.
        /// </summary>
        public static string awaitingApproval {
            get {
                return ResourceManager.GetString("awaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string btnApprove {
            get {
                return ResourceManager.GetString("btnApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่อนุมัติ.
        /// </summary>
        public static string btnReject {
            get {
                return ResourceManager.GetString("btnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyName.
        /// </summary>
        public static string compName {
            get {
                return ResourceManager.GetString("compName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th-TH.
        /// </summary>
        public static string cultureLocal {
            get {
                return ResourceManager.GetString("cultureLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการเช็ค.
        /// </summary>
        public static string dateOfCheque {
            get {
                return ResourceManager.GetString("dateOfCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เคลียร์เงินทดรองในวันที่.
        /// </summary>
        public static string dateOfPaymentSettlement {
            get {
                return ResourceManager.GetString("dateOfPaymentSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียน เพื่อดำเนินการ.
        /// </summary>
        public static string dearForProcess {
            get {
                return ResourceManager.GetString("dearForProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียน เพื่อทราบ.
        /// </summary>
        public static string dearToInform {
            get {
                return ResourceManager.GetString("dearToInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการ.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        public static string documentDate {
            get {
                return ResourceManager.GetString("documentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่.
        /// </summary>
        public static string documentNo {
            get {
                return ResourceManager.GetString("documentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบลายเซ็นของคุณในระบบ.
        /// </summary>
        public static string dontFoundYourSignatureInSystem {
            get {
                return ResourceManager.GetString("dontFoundYourSignatureInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nameTH.
        /// </summary>
        public static string dropdownStatus {
            get {
                return ResourceManager.GetString("dropdownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bu.
        /// </summary>
        public static string empBu {
            get {
                return ResourceManager.GetString("empBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyName.
        /// </summary>
        public static string empCompName {
            get {
                return ResourceManager.GetString("empCompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to department.
        /// </summary>
        public static string empDepartment {
            get {
                return ResourceManager.GetString("empDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสพนักงาน.
        /// </summary>
        public static string empId {
            get {
                return ResourceManager.GetString("empId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empName.
        /// </summary>
        public static string empName {
            get {
                return ResourceManager.GetString("empName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        public static string empPosition {
            get {
                return ResourceManager.GetString("empPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formName.
        /// </summary>
        public static string formName {
            get {
                return ResourceManager.GetString("formName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าใช้จ่าย.
        /// </summary>
        public static string headerTableCost {
            get {
                return ResourceManager.GetString("headerTableCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่ส่งอนุมัติ.
        /// </summary>
        public static string headerTableDateRequest {
            get {
                return ResourceManager.GetString("headerTableDateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัตถุประสงค์.
        /// </summary>
        public static string headerTableObjective {
            get {
                return ResourceManager.GetString("headerTableObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดขายช่วงกิจกรรม.
        /// </summary>
        public static string headerTableSales {
            get {
                return ResourceManager.GetString("headerTableSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % ต่อยอดขาย.
        /// </summary>
        public static string headerTableSalesPercent {
            get {
                return ResourceManager.GetString("headerTableSalesPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มลายเซ็นในระบบ.
        /// </summary>
        public static string insertYourSignature {
            get {
                return ResourceManager.GetString("insertYourSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่องาน.
        /// </summary>
        public static string jobName {
            get {
                return ResourceManager.GetString("jobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถบันทึกได้ ไฟล์อัพโหลดสูงสุดไม่เกิน.
        /// </summary>
        public static string msgMaximumFilesSave {
            get {
                return ResourceManager.GetString("msgMaximumFilesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่อนุมัติ.
        /// </summary>
        public static string notApprove {
            get {
                return ResourceManager.GetString("notApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกินกำหนด.
        /// </summary>
        public static string overdue {
            get {
                return ResourceManager.GetString("overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้รับเงิน.
        /// </summary>
        public static string payee {
            get {
                return ResourceManager.GetString("payee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้จ่ายเงิน.
        /// </summary>
        public static string payer {
            get {
                return ResourceManager.GetString("payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ความเร่งด่วน.
        /// </summary>
        public static string piorityDoc {
            get {
                return ResourceManager.GetString("piorityDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเพิ่มลายเซ็นก่อนอนุมัติเอกสาร.
        /// </summary>
        public static string pleaseInsertYourSignatureBeforeApprovalDocument {
            get {
                return ResourceManager.GetString("pleaseInsertYourSignatureBeforeApprovalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำแหน่ง.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัตถุประสงค์.
        /// </summary>
        public static string purpose {
            get {
                return ResourceManager.GetString("purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เหตุผล.
        /// </summary>
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อผู้ขอยืม.
        /// </summary>
        public static string requestByName {
            get {
                return ResourceManager.GetString("requestByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ แนบหลักฐานใบยืมเงินทดรองมาด้วยตอนเคลียร์เงิน.
        /// </summary>
        public static string textDetailsAttachPay {
            get {
                return ResourceManager.GetString("textDetailsAttachPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โดยมีรายละเอียดประมาณการค่าใช้จ่ายดังนี้.
        /// </summary>
        public static string theEstimatedExpenseDetailsAsPerFollowing {
            get {
                return ResourceManager.GetString("theEstimatedExpenseDetailsAsPerFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพื่ออนุมัติ.
        /// </summary>
        public static string toApproveDocument {
            get {
                return ResourceManager.GetString("toApproveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียน.
        /// </summary>
        public static string toDocument {
            get {
                return ResourceManager.GetString("toDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติอนุมัติ.
        /// </summary>
        public static string toHistoryAppprove {
            get {
                return ResourceManager.GetString("toHistoryAppprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จ่ายให้.
        /// </summary>
        public static string toPay {
            get {
                return ResourceManager.GetString("toPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวม.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รวมเงิน(บาท).
        /// </summary>
        public static string totalAmountTHB {
            get {
                return ResourceManager.GetString("totalAmountTHB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูเอกสาร.
        /// </summary>
        public static string toViewDocument {
            get {
                return ResourceManager.GetString("toViewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ตรวจสอบ.
        /// </summary>
        public static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำแนะนำการขอเบิกค่าใช้จ่าย.
        /// </summary>
        public static string viewManual {
            get {
                return ResourceManager.GetString("viewManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเอกสารที่คุณสร้าง.
        /// </summary>
        public static string yourCreatedDocuments {
            get {
                return ResourceManager.GetString("yourCreatedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเอกสารที่ได้รับการอนุมัติเรียบร้อย.
        /// </summary>
        public static string yourDocumentsApproved {
            get {
                return ResourceManager.GetString("yourDocumentsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเอกสารที่รอการอนุมัติ.
        /// </summary>
        public static string yourDocumentsAwaitingApproval {
            get {
                return ResourceManager.GetString("yourDocumentsAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลายเซ็นปัจจุบัน.
        /// </summary>
        public static string yourSignature {
            get {
                return ResourceManager.GetString("yourSignature", resourceCulture);
            }
        }
    }
}
