//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eActForm.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารทั้งหมด.
        /// </summary>
        public static string allDocuments {
            get {
                return ResourceManager.GetString("allDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การอนุมัติ.
        /// </summary>
        public static string approval {
            get {
                return ResourceManager.GetString("approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เอกสารขออนุมัติ.
        /// </summary>
        public static string approvalDocument {
            get {
                return ResourceManager.GetString("approvalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติการอนุมัติ.
        /// </summary>
        public static string approvalHistory {
            get {
                return ResourceManager.GetString("approvalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อนุมัติ.
        /// </summary>
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่อนุมัติ.
        /// </summary>
        public static string approveDate {
            get {
                return ResourceManager.GetString("approveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รออนุมัติ.
        /// </summary>
        public static string awaitingApproval {
            get {
                return ResourceManager.GetString("awaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyName.
        /// </summary>
        public static string compName {
            get {
                return ResourceManager.GetString("compName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th-TH.
        /// </summary>
        public static string cultureLocal {
            get {
                return ResourceManager.GetString("cultureLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียน เพื่อทราบ.
        /// </summary>
        public static string dearToInform {
            get {
                return ResourceManager.GetString("dearToInform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบลายเซ็นของคุณในระบบ.
        /// </summary>
        public static string dontFoundYourSignatureInSystem {
            get {
                return ResourceManager.GetString("dontFoundYourSignatureInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nameTH.
        /// </summary>
        public static string dropdownStatus {
            get {
                return ResourceManager.GetString("dropdownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bu.
        /// </summary>
        public static string empBu {
            get {
                return ResourceManager.GetString("empBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to companyName.
        /// </summary>
        public static string empCompName {
            get {
                return ResourceManager.GetString("empCompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to department.
        /// </summary>
        public static string empDepartment {
            get {
                return ResourceManager.GetString("empDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empName.
        /// </summary>
        public static string empName {
            get {
                return ResourceManager.GetString("empName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position.
        /// </summary>
        public static string empPosition {
            get {
                return ResourceManager.GetString("empPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formName.
        /// </summary>
        public static string formName {
            get {
                return ResourceManager.GetString("formName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค่าใช้จ่าย.
        /// </summary>
        public static string headerTableCost {
            get {
                return ResourceManager.GetString("headerTableCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัตถุประสงค์.
        /// </summary>
        public static string headerTableObjective {
            get {
                return ResourceManager.GetString("headerTableObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยอดขายช่วงกิจกรรม.
        /// </summary>
        public static string headerTableSales {
            get {
                return ResourceManager.GetString("headerTableSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % ต่อยอดขาย.
        /// </summary>
        public static string headerTableSalesPercent {
            get {
                return ResourceManager.GetString("headerTableSalesPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มลายเซ็นในระบบ.
        /// </summary>
        public static string insertYourSignature {
            get {
                return ResourceManager.GetString("insertYourSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่อนุมัติ.
        /// </summary>
        public static string notApprove {
            get {
                return ResourceManager.GetString("notApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกินกำหนด.
        /// </summary>
        public static string overdue {
            get {
                return ResourceManager.GetString("overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาเพิ่มลายเซ็นก่อนอนุมัติเอกสาร.
        /// </summary>
        public static string pleaseInsertYourSignatureBeforeApprovalDocument {
            get {
                return ResourceManager.GetString("pleaseInsertYourSignatureBeforeApprovalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลำดับ.
        /// </summary>
        public static string rank {
            get {
                return ResourceManager.GetString("rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เหตุผล.
        /// </summary>
        public static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สถานะ.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพื่ออนุมัติ.
        /// </summary>
        public static string toApproveDocument {
            get {
                return ResourceManager.GetString("toApproveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียน.
        /// </summary>
        public static string toDocument {
            get {
                return ResourceManager.GetString("toDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดูเอกสาร.
        /// </summary>
        public static string toViewDocument {
            get {
                return ResourceManager.GetString("toViewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำแนะนำการขอเบิกค่าใช้จ่าย.
        /// </summary>
        public static string viewManual {
            get {
                return ResourceManager.GetString("viewManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเอกสารที่คุณสร้าง.
        /// </summary>
        public static string yourCreatedDocuments {
            get {
                return ResourceManager.GetString("yourCreatedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเอกสารที่ได้รับการอนุมัติเรียบร้อย.
        /// </summary>
        public static string yourDocumentsApproved {
            get {
                return ResourceManager.GetString("yourDocumentsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนเอกสารที่รอการอนุมัติ.
        /// </summary>
        public static string yourDocumentsAwaitingApproval {
            get {
                return ResourceManager.GetString("yourDocumentsAwaitingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลายเซ็นปัจจุบัน.
        /// </summary>
        public static string yourSignature {
            get {
                return ResourceManager.GetString("yourSignature", resourceCulture);
            }
        }
    }
}
